### ISSUE TITLE
Get Facebook Token For Tinder 

### ISSUE THREAD

**Issue by dmeldrum** [skipperbent/tinder-php-sdk#13]
Using the provided link to get a Tinder Facebook token returns an invalid URI. This used to work a few weeks ago,

**Comment by skipperbent** [comment]
Yeah it seems Tinder have changed the redirect_uri. This sucks; somebody needs to help my find a new way to authenticate :(

**Comment by dmeldrum** [comment]
hi:
     I found a website tinder++ still works and is using facbeook version 2.6. 
    Pulling it apart over the next few days. I’ll let you know if its useable.

**Comment by skipperbent** [comment]
Could be that the Facebook auth token is still valid. But please let me know if you find anything - and thanks for the help.

**Comment by hbrylkowski** [comment]
You can  use this method: http://words.alx.red/tinder-api-1-authorization/

**Comment by dmeldrum** [comment]
thanks I’ll have a read

**Comment by skipperbent** [comment]
I can't get the link to work. 

@hbrylkowski Please let me know if the method works for you so I can update the documentation.

**Comment by dmeldrum** [comment]
Hi;
    working on it now. Using PhantomJS as a mobile device to emulate signning into facebook then Authorising using the mobile path.

**Comment by skipperbent** [comment]
I've updated the documentation to explain how to obtain the Facebook access_token.

**Comment by dmeldrum** [comment]
thanks very cool
