### ISSUE TITLE
New Headers

### ISSUE THREAD

**Issue by teamcoltra** [skipperbent/tinder-php-sdk#19]
According to the GIST of the main curl / api info the updated headers are:
```   
         'Content-type: application/json',
            'app_version: 3',
            'platform: ios',
            'User-Agent: Tinder/3.0.4 (iPhone; iOS 7.1; Scale/2.00)',
            'os_version: 700001'
```

I am still getting 401 error with this, but this should be getting in the right direction.

**Comment by skipperbent** [comment]
Thanks for your feedback.

The headers has been updated in version 1.2.2.

/ Simon
